#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.19
#  in conjunction with Tcl version 8.6
#    Nov 24, 2018 10:54:17 PM IST  platform: Windows NT

import sys
import tkinter.messagebox as fmsgbox

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import TICTACTOE_support


def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1(root)
    TICTACTOE_support.init(root, top)
    root.mainloop()


w = None


def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel(root)
    top = Toplevel1(w)
    TICTACTOE_support.init(w, top, *args, **kwargs)
    return (w, top)


def destroy_Toplevel1():
    global w
    w.destroy()
    w = None


bclick = True


class Toplevel1:

    def doRefresh(self):
        global bclick
        self.Button1['text'] = ''
        self.Button2['text'] = ''
        self.Button3['text'] = ''
        self.Button4['text'] = ''
        self.Button5['text'] = ''
        self.Button6['text'] = ''
        self.Button7['text'] = ''
        self.Button8['text'] = ''
        self.Button9['text'] = ''
        bclick = True

    def checkTie(self):
        if (self.Button1['text'] != '' and self.Button2['text'] != '' and self.Button3['text'] != '' and
            self.Button4['text'] != '' and self.Button5['text'] != '' and self.Button6['text'] != '' and
                self.Button7['text'] != '' and self.Button8['text'] != '' and self.Button9['text'] != ''):
            fmsgbox.showinfo("", "Its A Tie!")
            self.doRefresh()

    def checkwin(self):
        if (self.Button1['text'] == 'X' and self.Button2['text'] == 'X' and self.Button3['text'] == 'X' or
            self.Button4['text'] == 'X' and self.Button5['text'] == 'X' and self.Button6['text'] == 'X' or
            self.Button7['text'] == 'X' and self.Button8['text'] == 'X' and self.Button9['text'] == 'X' or
            self.Button3['text'] == 'X' and self.Button5['text'] == 'X' and self.Button7['text'] == 'X' or
            self.Button1['text'] == 'X' and self.Button5['text'] == 'X' and self.Button9['text'] == 'X' or
            self.Button1['text'] == 'X' and self.Button4['text'] == 'X' and self.Button7['text'] == 'X' or
            self.Button2['text'] == 'X' and self.Button5['text'] == 'X' and self.Button8['text'] == 'X' or
                self.Button3['text'] == 'X' and self.Button6['text'] == 'X' and self.Button9['text'] == 'X'):
            fmsgbox.showinfo("Player X", "Winner is X !!!")
            self.doRefresh()
        elif(self.Button1['text'] == 'O' and self.Button2['text'] == 'O' and self.Button3['text'] == 'O' or
             self.Button4['text'] == 'O' and self.Button5['text'] == 'O' and self.Button6['text'] == 'O' or
             self.Button7['text'] == 'O' and self.Button8['text'] == 'O' and self.Button9['text'] == 'O' or
             self.Button3['text'] == 'O' and self.Button5['text'] == 'O' and self.Button7['text'] == 'O' or
             self.Button1['text'] == 'O' and self.Button5['text'] == 'O' and self.Button9['text'] == 'O' or
             self.Button1['text'] == 'O' and self.Button4['text'] == 'O' and self.Button7['text'] == 'O' or
             self.Button2['text'] == 'O' and self.Button5['text'] == 'O' and self.Button8['text'] == 'O' or
                self.Button3['text'] == 'O' and self.Button6['text'] == 'O' and self.Button9['text'] == 'O'):
            fmsgbox.showinfo("Player Y", "Winner is O !!!")
            self.doRefresh()

    def click1(self):
        global bclick
        if self.Button1['text'] == '' and bclick:
            self.Button1.configure(text='''X''')
            bclick = False
        elif self.Button1['text'] == '' and bclick is False:
            self.Button1.configure(text='''O''')
            bclick = True
        self.checkwin()
        self.checkTie()

    def click2(self):
        global bclick
        if self.Button2['text'] == '' and bclick:
            self.Button2.configure(text='''X''')
            bclick = False
        elif self.Button2['text'] == '' and bclick is False:
            self.Button2.configure(text='''O''')
            bclick = True
        self.checkwin()
        self.checkTie()

    def click3(self):
        global bclick
        if self.Button3['text'] == '' and bclick:
            self.Button3.configure(text='''X''')
            bclick = False
        elif self.Button3['text'] == '' and bclick is False:
            self.Button3.configure(text='''O''')
            bclick = True
        self.checkwin()
        self.checkTie()

    def click4(self):
        global bclick
        if self.Button4['text'] == '' and bclick:
            self.Button4.configure(text='''X''')
            bclick = False
        elif self.Button4['text'] == '' and bclick is False:
            self.Button4.configure(text='''O''')
            bclick = True
        self.checkwin()
        self.checkTie()

    def click5(self):
        global bclick
        if self.Button5['text'] == '' and bclick:
            self.Button5.configure(text='''X''')
            bclick = False
        elif self.Button5['text'] == '' and bclick is False:
            self.Button5.configure(text='''O''')
            bclick = True
        self.checkwin()
        self.checkTie()

    def click6(self):
        global bclick
        if self.Button6['text'] == '' and bclick:
            self.Button6.configure(text='''X''')
            bclick = False
        elif self.Button6['text'] == '' and bclick is False:
            self.Button6.configure(text='''O''')
            bclick = True
        self.checkwin()
        self.checkTie()

    def click7(self):
        global bclick
        if self.Button7['text'] == '' and bclick:
            self.Button7.configure(text='''X''')
            bclick = False
        elif self.Button7['text'] == '' and bclick is False:
            self.Button7.configure(text='''O''')
            bclick = True
        self.checkwin()
        self.checkTie()

    def click8(self):
        global bclick
        if self.Button8['text'] == '' and bclick:
            self.Button8.configure(text='''X''')
            bclick = False
        elif self.Button8['text'] == '' and bclick is False:
            self.Button8.configure(text='''O''')
            bclick = True
        self.checkwin()
        self.checkTie()

    def click9(self):
        global bclick
        if self.Button9['text'] == '' and bclick:
            self.Button9.configure(text='''X''')
            bclick = False
        elif self.Button9['text'] == '' and bclick is False:
            self.Button9.configure(text='''O''')
            bclick = True
        self.checkwin()
        self.checkTie()

    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9'  # X11 color: 'gray85'
        _ana1color = '#d9d9d9'  # X11 color: 'gray85'
        _ana2color = '#ececec'  # Closest X11 color: 'gray92'
        font10 = "-family {Lucida Calligraphy} -size 12 -weight bold "  \
            "-slant roman -underline 0 -overstrike 0"
        font11 = "-family Arial -size 20 -weight bold -slant roman "  \
            "-underline 1 -overstrike 0"
        font12 = "-family {Lucida Calligraphy} -size 14 -weight normal"  \
            " -slant roman -underline 1 -overstrike 0"
        font13 = "-family Arial -size 28 -weight bold -slant roman "  \
            "-underline 0 -overstrike 0"
        font14 = "-family Calibri -size 20 -weight bold -slant roman "  \
            "-underline 0 -overstrike 0"
        font15 = "-family Calibri -size 30 -weight bold -slant roman "  \
            "-underline 1 -overstrike 0"
        font16 = "-family Arial -size 12 -weight bold -slant roman "  \
            "-underline 0 -overstrike 0"
        font9 = "-family {Lucida Calligraphy} -size 9 -weight bold "  \
            "-slant roman -underline 0 -overstrike 0"

        top.geometry("638x450+500+159")
        top.title("Tic Tac Toe Game")
        top.configure(background="#000000")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.219, rely=-0.022, height=61, width=294)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#000000")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font15)
        self.Label1.configure(foreground="#FFFFFF")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''TIC-TAC-TOE''')

        self.Entry1 = tk.Entry(top)
        self.Entry1.place(relx=0.204, rely=0.111, height=20, relwidth=0.226)
        self.Entry1.configure(background="white")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(highlightbackground="#d9d9d9")
        self.Entry1.configure(highlightcolor="black")
        self.Entry1.configure(insertbackground="black")
        self.Entry1.configure(selectbackground="#c4c4c4")
        self.Entry1.configure(selectforeground="black")

        self.Label2 = tk.Label(top)
        self.Label2.place(relx=0.0, rely=0.111, height=21, width=114)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#000000")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font=font16)
        self.Label2.configure(foreground="#ffffff")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''Player Name''')

        self.Canvas1 = tk.Canvas(top)
        self.Canvas1.place(relx=0.031, rely=0.178, relheight=0.8, relwidth=0.564)

        self.Canvas1.configure(background="#9b291c")
        self.Canvas1.configure(borderwidth="2")
        self.Canvas1.configure(highlightbackground="#d9d9d9")
        self.Canvas1.configure(highlightcolor="black")
        self.Canvas1.configure(insertbackground="black")
        self.Canvas1.configure(relief='ridge')
        self.Canvas1.configure(selectbackground="#c4c4c4")
        self.Canvas1.configure(selectforeground="black")
        self.Canvas1.configure(width=125)

        self.Button1 = tk.Button(self.Canvas1)
        self.Button1.place(relx=0.028, rely=0.028, height=105, width=105)
        self.Button1.configure(activebackground="#ff4a98")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#ffffff")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0", command=self.click1)

        self.Button2 = tk.Button(self.Canvas1)
        self.Button2.place(relx=0.361, rely=0.028, height=105, width=105)
        self.Button2.configure(activebackground="#ff4a98")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#ffffff")
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0", command=self.click2)

        self.Button3 = tk.Button(self.Canvas1)
        self.Button3.place(relx=0.681, rely=0.028, height=105, width=105)
        self.Button3.configure(activebackground="#ff4a98")
        self.Button3.configure(activeforeground="#000000")
        self.Button3.configure(background="#ffffff")
        self.Button3.configure(disabledforeground="#a3a3a3")
        self.Button3.configure(foreground="#000000")
        self.Button3.configure(highlightbackground="#d9d9d9")
        self.Button3.configure(highlightcolor="black")
        self.Button3.configure(pady="0", command=self.click3)

        self.Button4 = tk.Button(self.Canvas1)
        self.Button4.place(relx=0.028, rely=0.361, height=105, width=105)
        self.Button4.configure(activebackground="#ff4a98")
        self.Button4.configure(activeforeground="#000000")
        self.Button4.configure(background="#ffffff")
        self.Button4.configure(disabledforeground="#a3a3a3")
        self.Button4.configure(foreground="#000000")
        self.Button4.configure(highlightbackground="#d9d9d9")
        self.Button4.configure(highlightcolor="black")
        self.Button4.configure(pady="0", command=self.click4)

        self.Button5 = tk.Button(self.Canvas1)
        self.Button5.place(relx=0.361, rely=0.361, height=105, width=105)
        self.Button5.configure(activebackground="#ff4a98")
        self.Button5.configure(activeforeground="#000000")
        self.Button5.configure(background="#ffffff")
        self.Button5.configure(disabledforeground="#a3a3a3")
        self.Button5.configure(foreground="#000000")
        self.Button5.configure(highlightbackground="#d9d9d9")
        self.Button5.configure(highlightcolor="black")
        self.Button5.configure(pady="0", command=self.click5)

        self.Button6 = tk.Button(self.Canvas1)
        self.Button6.place(relx=0.681, rely=0.361, height=105, width=105)
        self.Button6.configure(activebackground="#ff4a98")
        self.Button6.configure(activeforeground="#000000")
        self.Button6.configure(background="#ffffff")
        self.Button6.configure(disabledforeground="#a3a3a3")
        self.Button6.configure(foreground="#000000")
        self.Button6.configure(highlightbackground="#d9d9d9")
        self.Button6.configure(highlightcolor="black")
        self.Button6.configure(pady="0", command=self.click6)

        self.Button7 = tk.Button(self.Canvas1)
        self.Button7.place(relx=0.028, rely=0.681, height=105, width=105)
        self.Button7.configure(activebackground="#ff4a98")
        self.Button7.configure(activeforeground="#000000")
        self.Button7.configure(background="#ffffff")
        self.Button7.configure(disabledforeground="#a3a3a3")
        self.Button7.configure(foreground="#000000")
        self.Button7.configure(highlightbackground="#d9d9d9")
        self.Button7.configure(highlightcolor="black")
        self.Button7.configure(pady="0", command=self.click7)

        self.Button8 = tk.Button(self.Canvas1)
        self.Button8.place(relx=0.361, rely=0.681, height=105, width=105)
        self.Button8.configure(activebackground="#ff4a98")
        self.Button8.configure(activeforeground="#000000")
        self.Button8.configure(background="#ffffff")
        self.Button8.configure(disabledforeground="#a3a3a3")
        self.Button8.configure(foreground="#000000")
        self.Button8.configure(highlightbackground="#d9d9d9")
        self.Button8.configure(highlightcolor="black")
        self.Button8.configure(pady="0", command=self.click8)

        self.Button9 = tk.Button(self.Canvas1)
        self.Button9.place(relx=0.681, rely=0.681, height=105, width=105)
        self.Button9.configure(activebackground="#ff4a98")
        self.Button9.configure(activeforeground="#000000")
        self.Button9.configure(background="#ffffff")
        self.Button9.configure(disabledforeground="#a3a3a3")
        self.Button9.configure(foreground="#000000")
        self.Button9.configure(highlightbackground="#d9d9d9")
        self.Button9.configure(highlightcolor="black")
        self.Button9.configure(pady="0", command=self.click9)

        self.Label2_17 = tk.Label(self.Canvas1)
        self.Label2_17.place(relx=0.833, rely=-0.111, height=21, width=64)
        self.Label2_17.configure(activebackground="#f9f9f9")
        self.Label2_17.configure(activeforeground="black")
        self.Label2_17.configure(background="#000000")
        self.Label2_17.configure(disabledforeground="#a3a3a3")
        self.Label2_17.configure(font=font16)
        self.Label2_17.configure(foreground="#ffffff")
        self.Label2_17.configure(highlightbackground="#d9d9d9")
        self.Label2_17.configure(highlightcolor="black")
        self.Label2_17.configure(text='''Turn''')

        self.Label3 = tk.Label(top)
        self.Label3.place(relx=0.627, rely=0.2, height=41, width=134)
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(activeforeground="black")
        self.Label3.configure(background="#000000")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(font=font11)
        self.Label3.configure(foreground="#ffffff")
        self.Label3.configure(highlightbackground="#d9d9d9")
        self.Label3.configure(highlightcolor="black")
        self.Label3.configure(text='''Result :''')

        self.menubar = tk.Menu(top, font="TkMenuFont", bg=_bgcolor, fg=_fgcolor)
        top.configure(menu=self.menubar)

        self.Entry3 = tk.Entry(top)
        self.Entry3.place(relx=0.658, rely=0.289, height=35, relwidth=0.32)
        self.Entry3.configure(background="white")
        self.Entry3.configure(disabledforeground="#a3a3a3")
        self.Entry3.configure(font="TkFixedFont")
        self.Entry3.configure(foreground="#000000")
        self.Entry3.configure(highlightbackground="#d9d9d9")
        self.Entry3.configure(highlightcolor="black")
        self.Entry3.configure(insertbackground="black")
        self.Entry3.configure(selectbackground="#c4c4c4")
        self.Entry3.configure(selectforeground="black")

        self.Message1 = tk.Message(top)
        self.Message1.place(relx=0.611, rely=0.511, relheight=0.051, relwidth=0.251)
        self.Message1.configure(background="#000000")
        self.Message1.configure(font=font12)
        self.Message1.configure(foreground="#ffffff")
        self.Message1.configure(highlightbackground="#d9d9d9")
        self.Message1.configure(highlightcolor="black")
        self.Message1.configure(text='''Developed By:''')
        self.Message1.configure(width=160)

        self.Message1_1 = tk.Message(top)
        self.Message1_1.place(relx=0.611, rely=0.378, relheight=0.051, relwidth=0.219)
        self.Message1_1.configure(background="#000000")
        self.Message1_1.configure(font=font12)
        self.Message1_1.configure(foreground="#ffffff")
        self.Message1_1.configure(highlightbackground="#d9d9d9")
        self.Message1_1.configure(highlightcolor="black")
        self.Message1_1.configure(text='''Guided By:''')
        self.Message1_1.configure(width=140)

        self.Message1_3 = tk.Message(top)
        self.Message1_3.place(relx=0.627, rely=0.444, relheight=0.051, relwidth=0.251)
        self.Message1_3.configure(background="#000000")
        self.Message1_3.configure(font=font10)
        self.Message1_3.configure(foreground="#ffffff")
        self.Message1_3.configure(highlightbackground="#d9d9d9")
        self.Message1_3.configure(highlightcolor="#000000")
        self.Message1_3.configure(text='''Nirmala Patil''')
        self.Message1_3.configure(width=160)

        self.Label4 = tk.Label(top)
        self.Label4.place(relx=0.627, rely=0.578, height=21, width=184)
        self.Label4.configure(activebackground="#f9f9f9")
        self.Label4.configure(activeforeground="black")
        self.Label4.configure(background="#000000")
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(font=font9)
        self.Label4.configure(foreground="#ffffff")
        self.Label4.configure(highlightbackground="#d9d9d9")
        self.Label4.configure(highlightcolor="black")
        self.Label4.configure(text='''-Akshaykumar Gunari''')

        self.Label4_4 = tk.Label(top)
        self.Label4_4.place(relx=0.611, rely=0.622, height=21, width=104)
        self.Label4_4.configure(activebackground="#f9f9f9")
        self.Label4_4.configure(activeforeground="black")
        self.Label4_4.configure(background="#000000")
        self.Label4_4.configure(disabledforeground="#a3a3a3")
        self.Label4_4.configure(font=font9)
        self.Label4_4.configure(foreground="#ffffff")
        self.Label4_4.configure(highlightbackground="#d9d9d9")
        self.Label4_4.configure(highlightcolor="black")
        self.Label4_4.configure(text='''-Gaurav J''')

        self.Label4_5 = tk.Label(top)
        self.Label4_5.place(relx=0.619, rely=0.667, height=21, width=114)
        self.Label4_5.configure(activebackground="#f9f9f9")
        self.Label4_5.configure(activeforeground="black")
        self.Label4_5.configure(background="#000000")
        self.Label4_5.configure(disabledforeground="#a3a3a3")
        self.Label4_5.configure(font=font9)
        self.Label4_5.configure(foreground="#ffffff")
        self.Label4_5.configure(highlightbackground="#d9d9d9")
        self.Label4_5.configure(highlightcolor="black")
        self.Label4_5.configure(text='''-Nitish Bhat''')

        self.Label4_6 = tk.Label(top)
        self.Label4_6.place(relx=0.611, rely=0.711, height=21, width=144)
        self.Label4_6.configure(activebackground="#f9f9f9")
        self.Label4_6.configure(activeforeground="black")
        self.Label4_6.configure(background="#000000")
        self.Label4_6.configure(disabledforeground="#a3a3a3")
        self.Label4_6.configure(font=font9)
        self.Label4_6.configure(foreground="#ffffff")
        self.Label4_6.configure(highlightbackground="#d9d9d9")
        self.Label4_6.configure(highlightcolor="black")
        self.Label4_6.configure(text='''-Akshata Patil''')

        self.Label4_7 = tk.Label(top)
        self.Label4_7.place(relx=0.627, rely=0.756, height=21, width=184)
        self.Label4_7.configure(activebackground="#f9f9f9")
        self.Label4_7.configure(activeforeground="black")
        self.Label4_7.configure(background="#000000")
        self.Label4_7.configure(disabledforeground="#a3a3a3")
        self.Label4_7.configure(font=font9)
        self.Label4_7.configure(foreground="#ffffff")
        self.Label4_7.configure(highlightbackground="#d9d9d9")
        self.Label4_7.configure(highlightcolor="black")
        self.Label4_7.configure(text='''-Anuradha Tasgaunkar''')

        self.Label4_8 = tk.Label(top)
        self.Label4_8.place(relx=0.627, rely=0.822, height=51, width=184)
        self.Label4_8.configure(activebackground="#f9f9f9")
        self.Label4_8.configure(activeforeground="black")
        self.Label4_8.configure(background="#000000")
        self.Label4_8.configure(disabledforeground="#a3a3a3")
        self.Label4_8.configure(font=font13)
        self.Label4_8.configure(foreground="#ff0a0a")
        self.Label4_8.configure(highlightbackground="#d9d9d9")
        self.Label4_8.configure(highlightcolor="black")
        self.Label4_8.configure(text='''KLE TECH''')

        self.Label2_18 = tk.Label(top)
        self.Label2_18.place(relx=0.439, rely=0.111, height=21, width=64)
        self.Label2_18.configure(activebackground="#f9f9f9")
        self.Label2_18.configure(activeforeground="black")
        self.Label2_18.configure(background="#000000")
        self.Label2_18.configure(disabledforeground="#a3a3a3")
        self.Label2_18.configure(font=font16)
        self.Label2_18.configure(foreground="#ffffff")
        self.Label2_18.configure(highlightbackground="#d9d9d9")
        self.Label2_18.configure(highlightcolor="black")
        self.Label2_18.configure(text='''Turn''')

        self.Entry2 = tk.Entry(top)
        self.Entry2.place(relx=0.533, rely=0.133, height=20, relwidth=0.163)
        self.Entry2.configure(background="white")
        self.Entry2.configure(disabledforeground="#a3a3a3")
        self.Entry2.configure(font="TkFixedFont")
        self.Entry2.configure(foreground="#000000")
        self.Entry2.configure(highlightbackground="#d9d9d9")
        self.Entry2.configure(highlightcolor="black")
        self.Entry2.configure(insertbackground="black")
        self.Entry2.configure(selectbackground="#c4c4c4")
        self.Entry2.configure(selectforeground="black")

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=0.721, rely=0.022, relheight=0.189, relwidth=0.188)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(background="#d8591a")
        self.Frame1.configure(highlightbackground="#d9d9d9")
        self.Frame1.configure(highlightcolor="#646464")
        self.Frame1.configure(width=120)

        self.Button2_15 = tk.Button(self.Frame1)
        self.Button2_15.place(relx=0.5, rely=0.353, height=50, width=50)
        self.Button2_15.configure(activebackground="#1dff0d")
        self.Button2_15.configure(activeforeground="#000000")
        self.Button2_15.configure(background="#a3632a")
        self.Button2_15.configure(disabledforeground="#a3a3a3")
        self.Button2_15.configure(font=font14)
        self.Button2_15.configure(foreground="#ffffff")
        self.Button2_15.configure(highlightbackground="#d9d9d9")
        self.Button2_15.configure(highlightcolor="black")
        self.Button2_15.configure(pady="0")
        self.Button2_15.configure(text='''Y''')

        self.Button2_4 = tk.Button(self.Frame1)
        self.Button2_4.place(relx=0.083, rely=0.353, height=50, width=50)
        self.Button2_4.configure(activebackground="#1dff0d")
        self.Button2_4.configure(activeforeground="#000000")
        self.Button2_4.configure(background="#a3632a")
        self.Button2_4.configure(disabledforeground="#a3a3a3")
        self.Button2_4.configure(font=font14)
        self.Button2_4.configure(foreground="#ffffff")
        self.Button2_4.configure(highlightbackground="#d9d9d9")
        self.Button2_4.configure(highlightcolor="black")
        self.Button2_4.configure(pady="0")
        self.Button2_4.configure(text='''Y''')

        self.Label2_16 = tk.Label(self.Frame1)
        self.Label2_16.place(relx=0.083, rely=0.059, height=21, width=64)
        self.Label2_16.configure(activebackground="#f9f9f9")
        self.Label2_16.configure(activeforeground="black")
        self.Label2_16.configure(background="#d8591a")
        self.Label2_16.configure(disabledforeground="#a3a3a3")
        self.Label2_16.configure(font=font16)
        self.Label2_16.configure(foreground="#ffffff")
        self.Label2_16.configure(highlightbackground="#d9d9d9")
        self.Label2_16.configure(highlightcolor="black")
        self.Label2_16.configure(text='''Choice''')


if __name__ == '__main__':
    vp_start_gui()
